@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AnnualVignette\n<size:10>oop.polymorph" as oop.polymorph.AnnualVignette [[AnnualVignette.html]] {
        +AnnualVignette(Date, String, String)
        +validUntil(): Date
        +isValid(): boolean
        +changePlate(String): boolean
    }

    abstract class "<size:14>VignetteBase\n<size:10>oop.polymorph" as oop.polymorph.VignetteBase [[VignetteBase.html]] {
        {abstract} +validUntil(): Date
        {abstract} +isValid(): boolean
    }
    interface "<size:14>ICanChangePlate\n<size:10>oop.polymorph" as oop.polymorph.ICanChangePlate [[ICanChangePlate.html]] {
        {abstract} +changePlate(String): boolean
    }

    oop.polymorph.VignetteBase <|-- oop.polymorph.AnnualVignette
    oop.polymorph.ICanChangePlate <|.. oop.polymorph.AnnualVignette

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
