@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ICanChangePlate\n<size:10>oop.polymorph" as oop.polymorph.ICanChangePlate [[ICanChangePlate.html]] {
        {abstract} +changePlate(String): boolean
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
