@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>VignetteBase\n<size:10>oop.polymorph" as oop.polymorph.VignetteBase [[VignetteBase.html]] {
        #startDate: Date
        #kfzType: String
        #plate: String
        +VignetteBase(Date, String)
        +VignetteBase(Date, String, String)
        +getPlate(): String
        {abstract} +validUntil(): Date
        +isExpired(): boolean
        {abstract} +isValid(): boolean
        +display(): String
        #getEndOfDay(Date): Date
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
