@startuml
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods

    oop.polymorph --> java.lang
    oop.polymorph --> java.util

    ' Package links
    class "oop.polymorph" [[oop/polymorph/package-summary.html]] {
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
